sonar.php.file.suffixes=.php
sonar.javascript.file.suffixes=.js
sonar.html.file.suffixes=.html
sonar.css.file.suffixes=.css
sonar.sourceEncoding=UTF-8
sonar.php.version=8.2
sonar.sources=app
sonar.language=php
sonar.host.url=http://localhost:9000
sonar.login=sqp_7bc22e76fe67ee16f983befaae945312d04aa173

# Exclusions
#sonar.exclusions=wp-admin/**,wp-includes/**,node_modules/**,vendor/**,wp-content/uploads/**

# Inclusions (specifically include custom themes and plugins)
#sonar.inclusions=wp-content/themes/**,wp-content/plugins/**
